# Sensitive passwords for ELK stack components
# In a real environment, use Ansible Vault for these secrets!
elastic_certs_password: "WorkshopCertsPass!" # Password for the p12 cert bundles
elastic_user_password: "ElkSecur3!"
kibana_user_password: "Kiban@Adm1n!"
logstash_user_password: "Logst@shSvc!"
beats_user_password: "BeatSvcPass!" # Not directly used by winlogbeat for logstash output, but set by elasticsearch-setup-passwords
apm_user_password: "ApmSvcPass!"
remote_monitoring_user_password: "Monit0rPass!"
